### PR TITLE
Add argument name check in preprocess_and_wrap, and fix dewpoint_from_specific_humidity

### PR DESCRIPTION
**Pull request by jthielen**
Here are the basic changes suggested in https://github.com/Unidata/MetPy/issues/2069!

### CODE REVIEW

**Review by dopplershift — APPROVED** [review]
Awesome, thanks for fixing. I half-expected this to catch some other lurking issues, but I assume not.

**Comment by dopplershift** [comment]
Uh....@jthielen somehow this ended up against *my* fork?

**Comment by dopplershift** [comment]
OH. Now I get it. You were adding to my solver branch. I'd be happy to just see this go in standalone since I'm not sure the solver will land for 1.2.

**Comment by jthielen** [comment]
> OH. Now I get it. You were adding to my solver branch. I'd be happy to just see this go in standalone since I'm not sure the solver will land for 1.2.

Yeah, I thought of it as a patch to the solver stuff, not an independent bug fix. Sorry about that! I'll rebase the change on Unidata/MetPy main and put in a regular PR.

**Comment by dopplershift** [comment]
No worries! It's not a bad thought, but really it's just that the solver helped discover the bug.

**Pull request closed without merging**
